

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_CHANGE_FORM_FIELDS = "LOGIN_CHANGE_FORM_FIELDS";
export const LOGIN_VALIDATE_FORM_FIELDS = "LOGIN_VALIDATE_FORM_FIELDS";
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGIN_VALIDATE_IPIN = "LOGIN_VALIDATE_IPIN";
export const LOGIN_VALIDATE_IPIN_SUCCESS = "LOGIN_VALIDATE_IPIN_SUCCESS";
export const LOGIN_VALIDATE_IPIN_FAIL = "LOGIN_VALIDATE_IPIN_FAIL";
export const LOGIN_CHANGE_IPIN_FORM_FIELDS = "LOGIN_CHANGE_IPIN_FORM_FIELDS";
export const LOGIN_VALIDATE_IPIN_FORM_FIELDS = "LOGIN_VALIDATE_IPIN_FORM_FIELDS";

export const LOGIN_PREFILL_FORM_FIELDS = "LOGIN_PREFILL_FORM_FIELDS";

export const LOGIN_FETCH_BRANDS = 'LOGIN_FETCH_BRANDS';
export const LOGIN_FETCH_BRANDS_SUCCESS = 'LOGIN_FETCH_BRANDS_SUCCESS';
export const LOGIN_FETCH_BRANDS_ERROR = 'LOGIN_FETCH_BRANDS_ERROR';

export const LOGIN_FETCH_LOCATIONS = 'LOGIN_FETCH_LOCATIONS';
export const LOGIN_FETCH_LOCATIONS_SUCCESS = 'LOGIN_FETCH_LOCATIONS_SUCCESS';
export const LOGIN_FETCH_LOCATIONS_ERROR = 'LOGIN_FETCH_LOCATIONS_ERROR';

export const FETCH_USER_DETAIL = 'FETCH_USER_DETAIL'
export const FETCH_USER_DETAIL_SUCCESS = 'FETCH_USER_DETAIL_SUCCESS'
export const FETCH_USER_DETAIL_FAIL = 'FETCH_USER_DETAIL_FAIL'
export const FETCH_USER_MENU_RIGHTS = 'FETCH_USER_MENU_RIGHTS'
export const FETCH_USER_MENU_RIGHTS_SUCCESS = 'FETCH_USER_MENU_RIGHTS_FAIL'
export const FETCH_USER_MENU_RIGHTS_FAIL = 'FETCH_USER_MENU_RIGHTS_FAIL'
export const SET_MODULE_NAV_BAR = 'SET_MODULE_NAV_BAR'
export const SET_USER_OPTION_NAV_BAR = 'SET_USER_OPTION_NAV_BAR'

export const GET_USER_MENU_SUB_GROUPS = 'GET_USER_MENU_SUB_GROUPS'

export const SET_MENU_OPTION_ON_BREADCRUMB = 'SET_MENU_OPTION_ON_BREADCRUMB'

export const AGENT_LOGIN = 'AGENT_LOGIN';
export const AGENT_LOGIN_SUCCESS = 'AGENT_LOGIN_SUCCESS';
export const AGENT_LOGIN_ERROR = 'AGENT_LOGIN_ERROR';

export const AGENT_LOGOUT = 'AGENT_LOGOUT';
export const AGENT_LOGOUT_SUCCESS = 'AGENT_LOGOUT_SUCCESS';
export const AGENT_LOGOUT_ERROR = 'AGENT_LOGOUT_ERROR';

export const AGENT_CALL_DIAL = 'AGENT_CALL_DIAL';
export const AGENT_CALL_DIAL_SUCCESS = 'AGENT_CALL_DIAL_SUCCESS';
export const AGENT_CALL_DIAL_ERROR = 'AGENT_CALL_DIAL_ERROR';


export const AGENT_CALL_END = 'AGENT_CALL_END';
export const AGENT_CALL_END_SUCCESS = 'AGENT_CALL_END_SUCCESS';
export const AGENT_CALL_END_ERROR = 'AGENT_CALL_END_ERROR';

export const AGENT_SET_MODE_CHANGE = 'AGENT_SET_MODE_CHANGE';
export const AGENT_SET_MODE_CHANGE_SUCCESS = 'AGENT_SET_MODE_CHANGE_SUCCESS';
export const AGENT_SET_MODE_CHANGE_ERROR = 'AGENT_SET_MODE_CHANGE_ERROR';

export const UNAUTHENTICATE_USER_TO_LOG_OUT = 'UNAUTHENTICATE_USER_TO_LOG_OUT'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'