export const FETCH_SERVICE_APPOINTMENT_SCREEN_INFO = 'FETCH_SERVICE_APPOINTMENT_SCREEN_INFO'
export const FETCH_SERVICE_APPOINTMENT_SCREEN_INFO_SUCCESS = 'FETCH_SERVICE_APPOINTMENT_SCREEN_INFO_SUCCESS'
export const FETCH_SERVICE_APPOINTMENT_SCREEN_INFO_ERROR = 'FETCH_SERVICE_APPOINTMENT_SCREEN_INFO_ERROR'

export const FETCH_DATA_POOL_DATA = 'FETCH_DATA_POOL_DATA' 

export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_POOL_DATA_SUCCESS = 'FETCH_DATA_POOL_DATA_SUCCESS'
export const FETCH_DATA_POOL_DATA_ERROR = 'FETCH_DATA_POOL_DATA_ERROR'

export const SET_DATAPOOL_CODE = 'SET_DATAPOOL_CODE'
export const SELECTED_FILTER_ITEM = 'SELECTED_FILTER_ITEM'
export const SELECTED_FOLLOWUP_EVENT_BUCKET = 'SELECTED_FOLLOWUP_EVENT_BUCKET'
export const SELECTED_CALLER = 'SELECTED_CALLER'

export const SET_PAGE_INDEX = 'SET_PAGE_INDEX'
export const FETCH_DATA_USING_CRITERIA = 'FETCH_DATA_USING_CRITERIA'
export const FETCH_DATA_USING_CRITERIA_SUCCESS = 'FETCH_DATA_USING_CRITERIA_SUCCESS'
export const FETCH_DATA_USING_CRITERIA_FAILURE = 'FETCH_DATA_USING_CRITERIA_FAILURE'

export const RESET_SERVICE_APPOINTMENT_VIEW_DATA = 'RESET_SERVICE_APPOINTMENT_VIEW_DATA'
export const FETCH_SERVICE_APPOINTMENT_DATA = 'FETCH_SERVICE_APPOINTMENT_DATA'
export const FETCH_SERVICE_APPOINTMENT_DATA_SUCCESS = 'FETCH_SERVICE_APPOINTMENT_DATA_SUCCESS'
export const FETCH_SERVICE_APPOINTMENT_DATA_FAILURE = 'FETCH_SERVICE_APPOINTMENT_DATA_FAILURE'

export const FETCH_SERVICE_APPOINTMENT_CALENDAR_VIEW_DATA = 'FETCH_SERVICE_APPOINTMENT_CALENDAR_VIEW_DATA'
export const FETCH_SERVICE_APPOINTMENT_CALENDAR_VIEW_DATA_SUCCESS = 'FETCH_SERVICE_APPOINTMENT_CALENDAR_VIEW_DATA_SUCCESS'
export const FETCH_SERVICE_APPOINTMENT_CALENDAR_VIEW_DATA_FAILURE = 'FETCH_SERVICE_APPOINTMENT_CALENDAR_VIEW_DATA_FAILURE'

export const FETCH_CUSTOMER_SERVICE_APPOINTMENT_DATA = 'FETCH_CUSTOMER_SERVICE_APPOINTMENT_DATA'
export const FETCH_CUSTOMER_SERVICE_APPOINTMENT_DATA_SUCCESS = 'FETCH_CUSTOMER_SERVICE_APPOINTMENT_DATA_SUCCESS'
export const FETCH_CUSTOMER_SERVICE_APPOINTMENT_DATA_FAILURE = 'FETCH_CUSTOMER_SERVICE_APPOINTMENT_DATA_FAILURE'

export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_CIRCULAR_LOADER = 'SHOW_CIRCULAR_LOADER'
export const HIDE_CIRCULAR_LOADER = 'HIDE_CIRCULAR_LOADER'

export const ADD_CUSTOMER_VOICE = 'ADD_CUSTOMER_VOICE'
export const DELETE_CUSTOMER_VOICE = 'DELETE_CUSTOMER_VOICE'

export const FETCH_DAYWISE_SERVICE_BOOKING_COUNT = 'FETCH_DAYWISE_SERVICE_BOOKING_COUNT'
export const FETCH_DAYWISE_SERVICE_BOOKING_COUNT_SUCCESS = 'FETCH_DAYWISE_SERVICE_BOOKING_COUNT_SUCCESS'
export const FETCH_DAYWISE_SERVICE_BOOKING_COUNT_FAILURE = 'FETCH_DAYWISE_SERVICE_BOOKING_COUNT_FAILURE'

export const FUP_MODAL_DATA_BY_VIN = 'FUP_MODAL_DATA_BY_VIN'
export const FUP_MODAL_DATA_BY_VIN_SUCCESS = 'FUP_MODAL_DATA_BY_VIN_SUCCESS'
export const FUP_MODAL_DATA_BY_VIN_FAILURE = 'FUP_MODAL_DATA_BY_VIN_FAILURE'

export const CREATE_SERVICE_APPOINTMENT = 'CREATE_SERVICE_APPOINTMENT'
export const CREATE_SERVICE_APPOINTMENT_SUCCESS = 'CREATE_SERVICE_APPOINTMENT_SUCCESS'
export const CREATE_SERVICE_APPOINTMENT_FAILURE = 'CREATE_SERVICE_APPOINTMENT_FAILURE'