export const FETCH_INBOUND_CRITERIA = "FETCH_INBOUND_CRITERIA";
export const FETCH_INBOUND_CRITERIA_SUCCESS = "FETCH_INBOUND_CRITERIA_SUCCESS";
export const FETCH_INBOUND_CRITERIA_FAILURE = "FETCH_INBOUND_CRITERIA_FAILURE";

export const FETCH_INBOUND_CASES_BY_CRITERIA =
  "FETCH_INBOUND_CASES_BY_CRITERIA";
export const FETCH_INBOUND_CASES_BY_CRITERIA_SUCCESS =
  "FETCH_INBOUND_CASES_BY_CRITERIA_SUCCESS";
export const FETCH_INBOUND_CASES_BY_CRITERIA_FAILURE =
  "FETCH_INBOUND_CASES_BY_CRITERIA_FAILURE";

export const FETCH_CREATE_NEW_CASE = "FETCH_CREATE_NEW_CASE";
export const FETCH_CREATE_NEW_CASE_SUCCESS = "FETCH_CREATE_NEW_CASE_SUCCESS";
export const FETCH_CREATE_NEW_CASE_FAILURE = "FETCH_CREATE_NEW_CASE_FAILURE";

export const FETCH_CUST_HISTORY_BY_IDENTIFICATION =
  "FETCH_CUST_HISTORY_BY_IDENTIFICATION";
export const FETCH_CUST_HISTORY_BY_IDENTIFICATION_SUCCESS =
  "FETCH_CUST_HISTORY_BY_IDENTIFICATION_SUCCESS";
export const FETCH_CUST_HISTORY_BY_IDENTIFICATION_FAILURE =
  "FETCH_CUST_HISTORY_BY_IDENTIFICATION_FAILURE";

export const GET_CUST_HISTORY_BY_IDENTIFICATION =
  "GET_CUST_HISTORY_BY_IDENTIFICATION";
export const GET_CUST_HISTORY_BY_IDENTIFICATION_SUCCESS =
  "GET_CUST_HISTORY_BY_IDENTIFICATION_SUCCESS";
export const GET_CUST_HISTORY_BY_IDENTIFICATION_FAILURE =
  "GET_CUST_HISTORY_BY_IDENTIFICATION_FAILURE";

export const FETCH_PROSPECT_HISTORY_BY_IDENTIFICATION =
  "FETCH_PROSPECT_HISTORY_BY_IDENTIFICATION";
export const FETCH_PROSPECT_DATASHEET_BY_IDENTIFICATION_SUCCESS =
  "FETCH_PROSPECT_DATASHEET_BY_IDENTIFICATION_SUCCESS";
export const FETCH_PROSPECT_DATASHEET_BY_IDENTIFICATION_FAILURE =
  "FETCH_PROSPECT_DATASHEET_BY_IDENTIFICATION_FAILURE";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SHOW_CIRCULAR_LOADER = "SHOW_CIRCULAR_LOADER";
export const HIDE_CIRCULAR_LOADER = "HIDE_CIRCULAR_LOADER";

export const SHOW_SALES_CUST_HISTORY_CIRCULAR_LOADER =
  "SHOW_SALES_CUST_HISTORY_CIRCULAR_LOADER";
export const HIDE_SALES_CUST_HISTORY_CIRCULAR_LOADER =
  "HIDE_SALES_CUST_HISTORY_CIRCULAR_LOADER";

export const SHOW_CASE_DATASHEET_CIRCULAR_LOADER =
  "SHOW_CASE_DATASHEET_CIRCULAR_LOADER";
export const HIDE_CASE_DATASHEET_CIRCULAR_LOADER =
  "HIDE_CASE_DATASHEET_CIRCULAR_LOADER";

export const CARD_DETAILS_TO_CALLER_INFORMATION =
  "CARD_DETAILS_TO_CALLER_INFORMATION";
export const CARD_DETAILS_TO_JOBCARD = "CARD_DETAILS_TO_JOBCARD";

export const SAVE_NEW_CASE = "SAVE_NEW_CASE";
export const SAVE_NEW_CASE_SUCCESS = "SAVE_NEW_CASE_SUCCESS";
export const SAVE_NEW_CASE_FAILURE = "SAVE_NEW_CASE_FAILURE";

export const FETCH_FUP_MODAL_DATA_BY_CASE_ID =
  "FETCH_FUP_MODAL_DATA_BY_CASE_ID";
export const FETCH_FUP_MODAL_DATA_BY_CASE_ID_SUCCESS =
  "FETCH_FUP_MODAL_DATA_BY_CASE_ID_SUCCESS";
export const FETCH_FUP_MODAL_DATA_BY_CASE_ID_FAILURE =
  "FETCH_FUP_MODAL_DATA_BY_CASE_ID_FAILURE";

export const OPEN_MODAL = "OPEN_MODAL";
export const EMPTY_API_RESPONSE = "EMPTY_API_RESPONSE";

export const FETCH_MANAGE_FOLLOW_UPS = "FETCH_MANAGE_FOLLOW_UPS";
export const FETCH_MANAGE_FOLLOW_UPS_SUCCESS =
  "FETCH_MANAGE_FOLLOW_UPS_SUCCESS";
export const FETCH_MANAGE_FOLLOW_UPS_FAILURE =
  "FETCH_MANAGE_FOLLOW_UPS_FAILURE";

export const SAVE_CASE_FOLLOW_UP = "SAVE_CASE_FOLLOW_UP";
export const SAVE_CASE_FOLLOW_UP_SUCCESS = "SAVE_CASE_FOLLOW_UP_SUCCESS";
export const SAVE_CASE_FOLLOW_UP_FAILURE = "SAVE_CASE_FOLLOW_UP_FAILURE";

export const HANDLE_NEXT_ACTION_DROPDOWN_LIST =
  "HANDLE_NEXT_ACTION_DROPDOWN_LIST";

export const UPDATE_UPLOADED_DOCUMENT_BALANCE_COUNT_SIZE =
  "UPDATE_UPLOADED_DOCUMENT_BALANCE_COUNT_SIZE";
export const UPDATE_MANAGE_FOLLOW_UP_UPLOADED_DOCUMENT_BALANCE_COUNT_SIZE =
  "UPDATE_MANAGE_FOLLOW_UP_UPLOADED_DOCUMENT_BALANCE_COUNT_SIZE";
export const TOGGLE_FORM_TYPE = "TOGGLE_FORM_TYPE";

export const ASSIGN_CASES_TO_USER = "ASSIGN_CASES_TO_USER";
export const ASSIGN_CASES_TO_USER_SUCCESS = "ASSIGN_CASES_TO_USER_SUCCESS";

export const ASSIGN_CASES_TO_USER_FAILURE = "ASSIGN_CASES_TO_USER_FAILURE";

export const EMPTY_INBOUND_CASES_LIST = "EMPTY_INBOUND_CASES_LIST";
export const EMPTY_CREATE_CASE_SCREEN = "EMPTY_CREATE_CASE_SCREEN";

export const FETCH_DEALER_OUTLET_INFO = "FETCH_DEALER_OUTLET_INFO";
export const FETCH_DEALER_OUTLET_INFO_SUCCESS =
  "FETCH_DEALER_OUTLET_INFO_SUCCESS";
export const FETCH_DEALER_OUTLET_INFO_FAILURE =
  "FETCH_DEALER_OUTLET_INFO_FAILURE";

export const OPEN_CLOSE_CREATE_CASE_CONTROL = "OPEN_CLOSE_CREATE_CASE_CONTROL";

export const INBOUND_FETCH_ENGAGED_CASES = " INBOUND_FETCH_ENGAGED_CASES";
export const INBOUND_FETCH_ENGAGED_CASES_SUCCESS =
  "INBOUND_FETCH_ENGAGED_CASES_SUCCESS";
export const INBOUND_FETCH_ENGAGED_CASES_FAILURE =
  "INBOUND_FETCH_ENGAGED_CASES_FAILURE";

export const EMPTY_ENGAGED_CASES = "EMPTY_ENGAGED_CASES";

export const OUTBOUND_FETCH_ENGAGED_CASES = "OUTBOUND_FETCH_ENGAGED_CASES";
export const OUTBOUND_FETCH_ENGAGED_CASES_SUCCESS =
  "OUTBOUND_FETCH_ENGAGED_CASES_SUCCESS";
export const OUTBOUND_FETCH_ENGAGED_CASES_FAILURE =
  "OUTBOUND_FETCH_ENGAGED_CASES_FAILURE";

export const REMOVE_UNLOCKED_CASES_FROM_LIST =
  "REMOVE_UNLOCKED_CASES_FROM_LIST";

export const SALES_CHECK_ACTIVE_CASES = "SALES_CHECK_ACTIVE_CASES";
export const SALES_CHECK_ACTIVE_CASES_SUCCESS =
  "SALES_CHECK_ACTIVE_CASES_SUCCESS";
export const SALES_CHECK_ACTIVE_CASES_FAILURE =
  "SALES_CHECK_ACTIVE_CASES_FAILURE";

export const SERVICE_CHECK_ACTIVE_CASES = "SERVICE_CHECK_ACTIVE_CASES";
export const SERVICE_CHECK_ACTIVE_CASES_SUCCESS =
  "SERVICE_CHECK_ACTIVE_CASES_SUCCESS";
export const SERVICE_CHECK_ACTIVE_CASES_FAILURE =
  "SERVICE_CHECK_ACTIVE_CASES_FAILURE";
