export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const OUTBOUND_CRITERIA = "OUTBOUND_CRITERIA";
export const OUTBOUND_CRITERIA_SUCCESS = "OUTBOUND_CRITERIA_SUCCESS";
export const OUTBOUND_CRITERIA_FAILURE = "OUTBOUND_CRITERIA_FAILURE";

export const OUTBOUND_CASES_BY_CRITERIA = "OUTBOUND_CASES_BY_CRITERIA";
export const OUTBOUND_CASES_BY_CRITERIA_SUCCESS =
  "OUTBOUND_CASES_BY_CRITERIA_SUCCESS";
export const OUTBOUND_CASES_BY_CRITERIA_FAILURE =
  "OUTBOUND_CASES_BY_CRITERIA_FAILURE";

export const OUTBOUND_CASE_BY_ID = "OUTBOUND_CASE_BY_ID";
export const OUTBOUND_CASE_BY_ID_SUCCESS = "OUTBOUND_CASE_BY_ID_SUCCESS";
export const OUTBOUND_CASE_BY_ID_FAILURE = "OUTBOUND_CASE_BY_ID_FAILURE";

export const EMPTY_OUTBOUND_CASES_LIST = "EMPTY_OUTBOUND_CASES_LIST";

export const CASE_DATASHEET = "CASE_DATASHEET";
export const CASE_DATASHEET_SUCCESS = "CASE_DATASHEET_SUCCESS";
export const CASE_DATASHEET_FAILURE = "CASE_DATASHEET_FAILURE";

export const SAVE_CASE_FOLLOW_UP = "SAVE_CASE_FOLLOW_UP";
export const SAVE_CASE_FOLLOW_UP_SUCCESS = "SAVE_CASE_FOLLOW_UP_SUCCESS";
export const SAVE_CASE_FOLLOW_UP_FAILURE = "SAVE_CASE_FOLLOW_UP_FAILURE";

export const OUTBOUND_FETCH_ENGAGED_CASES = "OUTBOUND_FETCH_ENGAGED_CASES";
export const OUTBOUND_FETCH_ENGAGED_CASES_SUCCESS =
  "OUTBOUND_FETCH_ENGAGED_CASES_SUCCESS";
export const OUTBOUND_FETCH_ENGAGED_CASES_FAILURE =
  "OUTBOUND_FETCH_ENGAGED_CASES_FAILURE";

export const EMPTY_ENGAGED_CASES = "EMPTY_ENGAGED_CASES";

export const CLOSED_CASES = "CLOSED_CASES";
export const CLOSED_CASES_SUCCESS = "CLOSED_CASES_SUCCESS";
export const CLOSED_CASES_FAILURE = "CLOSED_CASES_FAILURE";

export const EMPTY_CLOSED_CASES_LIST = "EMPTY_CLOSED_CASES_LIST";

export const SAVE_REOPENED_CASES = "SAVE_REOPENED_CASES";
export const SAVE_REOPENED_CASES_SUCCESS = "SAVE_REOPENED_CASES_SUCCESS";
export const SAVE_REOPENED_CASES_FAILURE = "SAVE_REOPENED_CASES_FAILURE";

export const REMOVE_REOPENED_CASES_FROM_LIST =
  "REMOVE_REOPENED_CASES_FROM_LIST";
export const OUTBOUND_SAVE_CASE_FOLLOW_UP = "OUTBOUND_SAVE_CASE_FOLLOW_UP";
export const OUTBOUND_SAVE_CASE_FOLLOW_UP_SUCCESS =
  "OUTBOUND_SAVE_CASE_FOLLOW_UP_SUCCESS";
export const OUTBOUND_SAVE_CASE_FOLLOW_UP_FAILURE =
  "OUTBOUND_SAVE_CASE_FOLLOW_UP_FAILURE";
export const ASSIGN_CASES_TO_USER_OUTBOUND_SUCCESS =
  "ASSIGN_CASES_TO_USER_OUTBOUND_SUCCESS";
export const EMPTY_API_RESPONSE_STATUS = "EMPTY_API_RESPONSE_STATUS";
